services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next15_ecommerce
    volumes:
      - postgres_data:/data/var/lib/postgresql/data

volumes:
  postgres_data:
