services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next15_ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next-ecommerce-network

networks:
  next-ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
